### ISSUE TITLE
css and js files doesn't seem to load

### ISSUE THREAD

**Issue by michapixel** [GCX/acf-address-field#2] opened 2012-04-27 08:05 UTC
I'm on wp 3.3.2 and use ACF Version 3.1.7 

and i get errors like:
"NetworkError: 403 Forbidden - http://localhost/wordpress_test/D:wampwwwwordpress_testwp-contentpluginsacf-address-field/address-field.css?ver=3.3.2"

**Comment by michapixel** [comment] 2012-04-27 10:06
well i got that fixed, but now i'm stuck. aren't the fields under 'Address Layout' supposed to be draggable? Shouldn't you even be able to drag them from row to row?

**Comment by sbone** [comment] 2012-04-28 22:45
I'm not experiencing any issues with files loading, however I'm running into the same issue with the Address Layout add-on. I cannot drag-and-drop any of the items around, and I'm not sure why. FF 11 and Chrome 18.0.1025.165.

**Comment by wyattjoh** [comment] 2012-05-01 02:18
Same Issue here as sbone.

**Comment by Omicron7** [comment] 2012-05-01 14:12
I haven't looked into it yet, but I updated to the latest Advanced Custom Fields yesterday and it looks like a lot of their javascript has changed. It may have broke the way I attached some events into the DOM.

**Comment by Omicron7** [comment] 2012-05-11 15:11
I've fixed the issue with drag/drop not working in the latest versions of ACF. Its in the development branch and will be included in the next release.

**Closed as completed by Omicron7** 2012-05-11 15:11 UTC

**Comment by michapixel** [comment] 2012-05-11 17:52
i'll try this version on monday. very cool!

**Comment by michapixel** [comment] 2012-05-14 07:44
again, this results in a network error:
NetworkError: 403 Forbidden - http://localhost/wordpress_test/D:wampwwwwordpress_testwp-contentpluginsadvanced-custom-fields-required-field-add-on/required-field.css?ver=3.3.2

**Comment by michapixel** [comment] 2012-05-14 10:09
whoa, i see, i've posted the wrong error here.

but it remains the same: somehow the path under windows for registering script and style is ttotally wrong and results in an error. 

ugly to debug, but i'll see what i can do about that.

**Comment by michapixel** [comment] 2012-05-14 10:10
you should reopne this issue, as this has not been fixed.

**Comment by michapixel** [comment] 2012-05-14 10:46
ok: the uri you need is in both cases: $uri = plugin_dir_url(**FILE**);

so 
"wp_register_style( 'acf-address-field', $uri . '/address-field.css' );" that fixes all issues.

**Comment by Omicron7** [comment] 2012-05-14 14:46
michapixel, that's a great fix if this add-on was designed solely as a WordPress plugin. It isn't. The add-on is designed to function as a WordPress plugin as well as a drop-in into themes or other plugins. The `plugin_dir_url()` method only works when the add-on is installed as a WordPress plugin or as a drop-in to another plugin. It does not generate the correct URI when the add-on is inside a theme.

The second issue is that `plugin_dir_url()` doesn't work in complex WordPress installs, primarily when symlinks are used in the plugins directory.  PHP resolves symlinks for the `__FILE__` magic constant and when `plugin_dir_url()` searches for the `plugins` or `mu-plugins` string in the path, it may not exist and therefore can't create a url.

These are the 2 reasons I'm generating the URL for this add-on manually. I would rather fix the underlying issue you are experiencing on Windows than implement a fix (the `plugin_dir_url()` method) that would not work in all scenarios. I'll open a new issue stating your original issue as this one primarily turned into a Drag / Drop issue which should be fixed.

**Comment by michapixel** [comment] 2012-05-14 14:55
then tell me how i can help you to fix this issue.

**Comment by Omicron7** [comment] 2012-05-14 15:19
See #4
